### ISSUE TITLE
Crashes when I select on Overlay

### ISSUE THREAD

**Issue by Lord-Dargon** [XorTroll/emuiibo#112]
I've installed everything in the correct place then when I select "emuiibo" it crashes and give the error 
Error code: 2168-0002 (0x4a8)
Program: 0100000000000352
I don't really understand it well so I figured someone could help me here. If there's a better way I'll gladly move there. Thank you in advance.

**Comment by XorTroll** [comment]
Are you using the latest Atmosphere and emuiibo versions?

**Comment by hstraten** [comment]
I have the same issue after doing a clean install (upgrade) of Atmosphere 0.14.1 and HOS 10.1.0 (I tried an in-place upgrade but ran into issues running some games which turned out to be emuiibo related)
been a happy user of emuiibo in combination with amiigomod from StarDustCFW before that. (was on HOS 10.0.1 and ATM 0.13.0 before)
Looks like some games (Animal Crossing for instance that can use amiibo's do not start or crash)
When disabling the emuiibo sys module I can run these games fine.
Opening the overlay crashes immediately as mentioned by @Lord-Dargon 
I can reproduce the issue so I can run some tests when needed if you'd like.

**Comment by lookye** [comment]
The problem is known and it´s being worked on. It´s more than just a recompile bc the atmosphere-libs changed a lot.

**Comment by GabyH2O** [comment]
Hi, I am having the same problem with code 2168-0002 (0x4a8) when I try to activate emuiibo overlay.
I also found that if you install the emuiibo overlay, it will glitch animal crossing new leaf freezing the black screen in the black with the floating island. I fixed the animal crossing problem by deleting everything related to emuiibo in the sd card.
I am running an atmosphere 0.14.1 on firmware 10.1.0. 

I hope you find a solution soon for emuiibo and the overlay problem.

**Comment by hyklvzm** [comment]
> I've installed everything in the correct place then when I select "emuiibo" it crashes and give the error
> Error code: 2168-0002 (0x4a8)
> Program: 0100000000000352
> I don't really understand it well so I figured someone could help me here. If there's a better way I'll gladly move there. Thank you in advance.

My condition is that everything works fine if using AMS defalt fusee secondary.bin, but if I switch to fusee primary.bin, the system just crashes after unlocking homescreen, hope this could help you

**Comment by lookye** [comment]
If that happens for you, you have different problems in your whole setup.

**Comment by hyklvzm** [comment]
Yeah I know something is wrong, but I followed the correct steps as well so I am just providing some feedback. BTW, I think the reason for homescreen crash is ldm_mitm because I turned it off then AMS  runs well using fusee primary，but when select emuiibo in overlay, AMS gives the same crash and same error code as @Lord-Dargon

**Comment by malekalhalabi** [comment]
I have the same issue, when I load emuiibo on tesla overlay my CFW crashes. I tried to re install atmosphere and I downloaded the latest version, still didn't work. Is there any fix to this? Or is there another amiibo emulator similar to emuiibo? I'm new to the switch hb scene and I've only worked on 3ds and wii homebrewing.

**Comment by malekalhalabi** [comment]
Ok I found out that Emuiibo does not work on 10.1.0 yet, and that is the reason for the crash (if your on 10.10) i have not tried it on any older software but I am pretty sure it does not work on 10.1.0. Can someone correct me if I'm wrong

**Comment by GabyH2O** [comment]
Do you have Animal Crossing installed? I am asking because I use 2 micro sd cards that I alternate for my switch and the only difference between them is the games installed on them. In the micro sd card (128gb)  that I only have a few games, emuiibo runs fine, but in the sd card (264gb) with animal crossing and multiple games that use amiibo, emuiibo overlay causes atmosphere to crash with the error code 2168-0002 (0x4a8).  I am running Atmosphère 0.14.2 on 10.1.0 switch and emuiibo 0.5.1

**Comment by malekalhalabi** [comment]
No i do not have Animal Crossing, but i found out that the latest version of Emuiibo does not work with Atmosphere 0.14.2 you will need to downgrade to 0.13.0 and make sure you delete the 0100000000000042 folder from sdroot\atmosphere\contents when you go to 0.13.0. If it does not work for you then im not sure how i can help but 0.13.0 works for me without any crashes. Hope this helps
