### ISSUE TITLE
Zelda Botw amiibos not working properly

### ISSUE THREAD

**Issue by andremelo90** [XorTroll/emuiibo#173]
Maybe i am doing something wrong, but when using amiibos in zelda botw usually on the 3rd amiibo all the other ones get locked saying it cannot be used again for the day. Can confirm up to 0.6.2 it did not happen.

Edit: solved, just did generate new amiibos with emutool.

**Comment by XorTroll** [comment]
BOTW doesn't allow using the same amiibo several times a day, that's why the "random UUID" option exists. Did you create your amiibos with that feature checked?

**Comment by andremelo90** [comment]
> BOTW doesn't allow using the same amiibo several times a day, that's why the "random UUID" option exists. Did you create your amiibos with that feature checked?

Yeah im aware of that, i always use all of them daily.. but the issue was that when using through them suddenly all the remaining (still not used on that day) would just give the message they have been used. But as i mentioned, generated new ones (without random UUID) solved.

**Comment by PKGaspi** [comment]
Same issue here. The problem is that, when generating all amiibos at once, some of them get the same UUID. As such, the game treats them as the same amiibo, even tho they represent different figurines (for example, link from majora's mask and link from ocarina of time). 

I don't know if this behaviour is intended, but different amiibos should have different UUIDs in my opinion to avoid this.
