### ISSUE TITLE
amiibo .bin to emuiibo format converter

### ISSUE THREAD

**Issue by jozz024** [XorTroll/emuiibo#187]
is there a preexisting program that can convert raw amiibo bin files to the format emuiibo uses? this would be useful for ssbu for the people who have already trained figures.

also i'm super sorry if this isn't the place for this, i just couldn't find a better place to put it.

**Comment by impeeza** [comment]
you need secret keys and [amiitool](https://github.com/socram8888/amiitool/releases/tag/r2) in order to decrypt the binary files, then split the content using a Hex editor.  For instructions you can read the corresponding section on [Readme.md](https://github.com/XorTroll/emuiibo#raw-dumps-and-encryption)

**Comment by XorTroll** [comment]
It might be a good idea to simplify/automate the process in emutool instead of having a simple written guide

**Comment by jozz024** [comment]
that would be very useful, would it be possible to derive the data from the amiibo bin to put in the amiibo.json too?

**Comment by impeeza** [comment]
but the users should provide the keys manully? that's correct?

**Comment by jozz024** [comment]
yes, the users would 100% need to provide the keys/key

**Comment by jozz024** [comment]
since i've already made a python script to convert the ryujinx format amiibo to .bin and back again, i may try to do the same for emuiibo.

**Comment by impeeza** [comment]
thanks a lot.
