### ISSUE TITLE
Issue building from source

### ISSUE THREAD

**Issue by Thrumptus** [XorTroll/emuiibo#219]
Tried building via both mac and wsl, the error appears to be when building the nsp  

[emuiibo.txt](https://github.com/XorTroll/emuiibo/files/9741958/emuiibo.txt)

**Comment by djskual** [comment]
i get this trying to compile:

`Building and generating NSP...
Triple: aarch64-nintendo-switch
error: failed to run "rustc" to learn about target-specific information

Caused by:
  process didn't exit successfully: "rustc - --crate-name ___ --print=file-names --target aarch64-ni
ntendo-switch --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type
 staticlib --crate-type proc-macro --print=sysroot --print=cfg" (exit code: 1)
  --- stderr
  error: Error loading target specification: invalid escape at line 10 column 26. Run "rustc --print
 target-list" for a list of built-in targets`

**Comment by urherenow** [comment]
I get that error in msys2, but I built it just fine in a Ubuntu VM.

The first error, I haven't seen on either. I can only suggest for that one (@Thrumptus) you need to make sure you have your tool chain updated ( (dkp)pacman-Syuu ). It appears your libnx is outdated.
