### ISSUE TITLE
emuiibo nonfunctional in fire emblem 3houses

### ISSUE THREAD

**Issue by kschwizzle** [XorTroll/emuiibo#41]
so i just downloaded emuiibo .3 and am having a spot of trouble getting it to work for fire emblem 3 houses (id test more on games, but all i have is BotW). I'm currently on 8.1 using ams 0.9.2, and i get the light on the home button when i toggle emuiibo on, but i just can't get any responsiveness out of the game. I've got the needed jsons in my amiibo's folder but can't get results. Any insights that could be offered are appreciated

**Comment by BananaSlayer** [comment]
I am having the same issue. My amiibo works with SSBU, but not with Three Houses.

**Comment by sw3d3r** [comment]
Emuiibo is broke. Waiting on an update but they are lagging super hard , seems they don't care, it's been almost 2months of issues and no rerelease, very dissapointed, I'll be back next week to check again :)

**Comment by XorTroll** [comment]
Three Houses probably handles amiibo differently. Stop blaming emuiibo, since I'm pretty much convinced emuiibo is working right. Not all games use amiibo stuff the same way...

**Comment by sw3d3r** [comment]
Hahaha have you even been on the amiiswap discord channel ?? Everyone and I will repeat "everyone" is having issues with emuiibo working on 0.9.3 with 8.1.0 just go take a glance at the discord channel it's been months of no emulation. Furybaguette of Amiiswap has said that emuiibo has messed with some things and now won't run properly. Amiiswap still works fine. But no one has been able to get emuiibo to run since the new atmosphere updates and new 8.1.0 firmware. I'm not trying to discredit you but I am one of those people and I have 10 different switch devices all emuiibo not working. I tried the latest version and older version and the light on right joycon flashes but nothing changes in game. And emulation has been enabled. I'm not the only one. I'm speaking for many. I'm not here to argue just bring light to issues .... Please update emuiibo thank you

**Comment by lookye** [comment]
Offtopic: 
Funnily emuiibo 0.3 works fine for me on 8.1.
Amiiswap is the thing that needs to be updated to work with emuiibo 0.3 and its also just a optional thing. If you dont know how to use it you should take a look into the readme/changelog.

And tbh: Yes, emuiibo + FE3H does not work instantly.

**Comment by detuur** [comment]
It works, but you have to have patience. Make sure emuiibo is enabled before starting FETH, the button combos also work in the homescreen. Then when you use the Amiibo Gazebo, just give it some time. It can take several minutes for the game to scan the virtual amiibo. Mine took maybe 5 minutes, I just left it on the "Please hold the amiibo to the NFC area" screen while I was doing something else.

**Comment by cryptolute** [comment]
sw3d3r - It appears that xortroll/furybagel have no intention of offering support for this issue despite acknolwedging it IS a issue. I tried asking in the amiiswap discord only to have elitest shit-attitudes spewed back to me - "Does this look like the emuiibo support channel"? 

Well, if your tool relies upon the content generated by emuiibo, you'll definitely get questions about emuiibo within the context of how it works with amiiswap, so maybe just acknowledge this fact and get over it instead of acting outraged that someone came to your discord and asked a question in #support

In short - These guys are overly-sensitive children about their software. Any suggestion that their software might not be fully functional or compatible will get you immature and/or hostile responses. If you don't want to support your software thats fine.....don't run a discord channel offering support then.

I think the only thing thats going on here is human's with a lack of motivation to update their software either because they are incapable of it, or they are too lazy to spend the time doing it. Instead of just acknowledging this, they want to lash out at the people pointing out the flaws. Seriously devs - grow up. Its perfectly fine to have bugs and non-functioning software, just acknowledge its a WIP, say its broke and clarify that you're not offering support on the issue. Don't pretend your offering support and then lash out at people when they ask fair questions.

**Comment by cryptolute** [comment]
Good news guys. Thanks to mrdude you can now get (some) FE amiibo's working. Simply use his modded version of emuguiibo to generate the added FETH amiibo's (4 available in this build) -

https://gbatemp.net/threads/modded-emuguiibo.548485/

put generated files in on SD in /emuiibo/amiibo/generated-dir-here

i just successfully scanned a FE amiibo on emuiibo 0.3.1 on atmos (using atlasnx 14.2 with joonie sigpatches) with OFW 8.x

Took about 10-15 seconds for the amiibo to be recognized but it worked!

If you want to use amiiswap to check the status and verify that emuiibo is functioning correctly use his amiiswap mod here which works with 0.3.1 emuiibo -

https://gbatemp.net/threads/amiiswap-mod-for-emuiibo-0-3.548465

Also.....really good advice mrdude said right here to keep in mind -

"Most likely when you are switching amiibos - you are not disabling then re-enabling them, you need to do that for the changes to take effect as the old amiibo details are cached, this is down to the way emuiibo works.

For example, when you switch from Mario to Mario Wedding - disable then enable the emiibo as well for the changes to be noticed."

Im REALLY thankful to mrdude. He was chill and helpful and fixed the nonsense that furybagel and xortroll can't be bothered with.

Honestly both have been overly-sensitive man-children about these issues. Either refusing to acknowledge they exist, or if they do exist saying its basically not their problem (lol, thats helpful!). Or, with furybagel, when asking about emuguiibo generated content, responding with hostility when asked questions about emuiibo/amiiswap crossover.

These dev's are not the most competent individuals and when you point out issues instead of responding like mature adults about it they get as sensitive as a newly woke white woman when she hears a racially sensitive term being used.

devs need to grow a pair and learn how to accept when their software is broken and not lash out at end users for asking questions.

**Comment by XorTroll** [comment]
Lol, someone looks mad. FYI, developers have a life, and often, other projets to work on.
Now I'm busy working on other stuff, I will look into it when I can.
However I should take also a look on that "cached amiibos" matter

**Comment by detuur** [comment]
Jesus the entitlement to a free thing someone spent his free time on is mind-boggling. Stark reminder that most pirates are pirates because they have no respect for someone else's work and effort. @XorTroll take your time with this. emuiibo works in fe3h, just very slowly. Thanks for your efforts.

**Comment by cryptolute** [comment]
0.3.1 emuiibo does not properly extract and move json content to the /emuiibo/amiibo folders when booted with a bin in the emuiibo for.  It does not "work fine" as that is a prerequisite to it's functionality. 

If you use the emuguiibo pc mod mrdude posted it has some FETH profiles built in allowing me to confirm it works on both 0.3.1 and amiiswap mod by mrdude.

In short all of the entirety of this problem is caused by the fact that 0.3.1 is not correctly creating json content from original bin files. 

Pretending problems don't exist doesn't fix them. And punishing end users for pointing out issues only delays fixing of those items. Tribalism is just as toxic. I've supported xortroll on forums for years now when others attacked him...but everyone makes mistakes and has issues crop up. This isn't exactly commercial FOSS environment. It's one dude with spare time. 

If I post you my limited edition fire emblem set I paid nearly $200 for are you going to take back calling me a pirate?

**Comment by detuur** [comment]
So you're saying your overblown sense of self-importance and entitlement _isn't_ because you're a pirate? Because sure, I'll give you that.

**Comment by cryptolute** [comment]
Update - mrdude has posted a new emuguiibo that allows for original bin to json conversion. So this is a solution for anyone who want the additional fire emblem amiibo's not present in the app to get working versions.

https://gbatemp.net/threads/modded-emuguiibo.548485

**Comment by XorTroll** [comment]
Fixed for the next version :)
