### ISSUE TITLE
9.0 system & 0.94 atmosphere have some problems

### ISSUE THREAD

**Issue by LZQ0803FSX** [XorTroll/emuiibo#47]
i use the latest emuiibo and AmiiSwap1.0 and i have set up emuiibo folder and put into bin files according to instruction, but it show me List is Empty after selecting Amiibos->All in AmiiSwap . 
And there are some empty folders in sd/emuiibo/amiibo, is this situation normal, what should i do.
Forgive my poor English.

**Comment by wicksand420** [comment]
Did you do this? You also have to set the boot2 flag in the CFW's /titles directory: <cfw>/titles/0100000000000352/flags/boot2.flag

**Comment by LZQ0803FSX** [comment]
![微信图片_20190922133302](https://user-images.githubusercontent.com/23418195/65382710-8a077980-dd3d-11e9-911d-836eed1a703f.jpg)
do you mean this? boot2.flag is a empty file

**Comment by LZQ0803FSX** [comment]
> Did you do this? You also have to set the boot2 flag in the CFW's /titles directory: atmosphere/titles/0100000000000352/flags/boot2.flag

![微信图片_20190922133302](https://user-images.githubusercontent.com/23418195/65382740-f3878800-dd3d-11e9-94a4-b873fb925d56.jpg)
do you mean this? boot2.flag is an empty file

**Comment by wicksand420** [comment]
Yep, that's what I meant, its supposed to be a blank file I believe.

**Comment by wicksand420** [comment]
did you use emuGUIibo.zip to set up your amiibos?

**Comment by LZQ0803FSX** [comment]
> Yep, that's what I meant, its supposed to be a blank file I believe.

Uhh..... but it was set up like this before, so i still dont know what to do.

**Comment by LZQ0803FSX** [comment]
> did you use emuGUIibo.zip to set up your amiibos?

I just tried it and dont know whether i did it right. i got a filefolder with four json files by using emuGUiibo and put the filefolder into sd/emuiibo/amiibo, then i open AmiiSwap, The problem is still not solved. i dont know whether i did it right.

**Comment by lookye** [comment]
@LZQ0803FSX 
> i use the latest emuiibo and AmiiSwap1.0
AmiiSwap does not work together with the latest two emuiibo versions.

**Comment by An70ni092** [comment]
> @LZQ0803FSX
> 
> > i use the latest emuiibo and AmiiSwap1.0
> > AmiiSwap does not work together with the latest two emuiibo versions.

Don't even go without AmiiSwaps...

**Comment by lookye** [comment]
Of course does it work without amiiswap. You need to use the button combos that are stated in the readme.

**Comment by An70ni092** [comment]
> Of course does it work without amiiswap. You need to use the button combos that are stated in the readme.

That's what I do but it doesn't work, I followed the readme file step by step

**Comment by Kyamon** [comment]
Seems like @An70ni092 is having the same issue as I am. Button combos seem to do nothing.

**Comment by An70ni092** [comment]
> Seems like @An70ni092 is having the same issue as I am. Button combos seem to do nothing.

Then I'm not alone...

**Comment by NettoHikari** [comment]
Same here. Followed the readme 1:1, button combos don't work. Home button flashes, but no effect in Link's Awakening.

**Comment by An70ni092** [comment]
Odyssey
Breath of the Wild
Link's Awakening

**Comment by TheNarutimate11** [comment]
The atmosphere gives me a mistake if I install the emuiibo. I use system v9.0.1, atmosphere 0.9.4 and an SD in exFat

**Comment by pr0dukt** [comment]
Get off exfat for starters. its seriously one of the biggest core problems to a plethora of switch brew related issues. even if isn't the root cause in this particular case, its always a damn good first step to isolating potential issues. I can't help but cringe when a layman user starts ranting off an issue with the repeated reassurance that the 'procedural literature' was followed letter to letter, and then ends the indignant spiel on "latest ver bleh, on ver. bleh, with bleh cfw installed on an **exfat** formatted sd card desu... waht cud i posibleh bae doeng rong dat alwayz fucz up mah switch up?! des devs need git et taguthar, amirite?!"
It's just common sense at this point, if you want the most painless-as-possible experience with the use of homebrew on a switch utilizing unorthodox methods of functionality, despite its fragile state of stability, which is just by nature when using CFW, then you have to use the file format that the  architects of these very functions and utilities are telling you work the most reliably. >.<

I wish people would have just made formatting thier SD cards prior to installing AMS or SX, a pre-requisite back in the day. I feel like a good 65% of brew-related issues would have been resolved right then and there. :p lol alas, ,making things easy for ourselves has never been a natural inclination for us humans i suppose...

**Comment by PKPenguin321** [comment]
Button combos seem to be entirely broken on latest atmos/system FW. Home button does not flash, the game I am in does not matter. Amiigo seems to work for enabling emulation and choosing an amiibo but it's much less convenient than button combos.

**Comment by XorTroll** [comment]
Next version is getting rid of them

**Comment by RampageGod** [comment]
Dear mr. XorTroll,
really needyour help with Emuiibo. I've put in Emuiibo folder in SD folder, but it still doesn't work. AmiSwap doesn't help either, it just say that Emuiibo is not installed. I'm confused, tried to copy or download Emuiibo from different resources, but nothing seems work or help. Uptdate to 9.2.0 & Atmo 0.11.1 doesn't help the issue remains. I will apreciate your help!
