### ISSUE TITLE
Possible idea: implement bin dump decryption

### ISSUE THREAD

**Issue by XorTroll** [XorTroll/emuiibo#86]
This would allow dumping a lot of content from amiibo bin dumps, and allowing cases like the 20 heart wolf link work fine without having to get them manually.
Problem - the retail key is needed, and the only solution I can think of is to ask the user to place the key (something like `sd:/emuiibo/key_retail.bin`)

I'm open to any suggestions on this topic

**Comment by urherenow** [comment]
Thenaya for 3ds already does this. The other benefit with thenaya is that it can WRITE amiibos to NFC stickers, so troublesome games like BoTW, aren’t an issue, since there is no need to emulate the amiibo, if you can simply make one.

In SD root, you add amiibo_keys.bin. That isn’t quite the name to google to actually get the keys though (doubt you want me to get too specific here) needs the term “retail”...

See: https://github.com/HiddenRamblings/Thenaya

**Comment by XorTroll** [comment]
Yeah, basically this is what I have in my mind, like Thenaya does, using amiitool's decryption code.

**Comment by JaySea77** [comment]
This would be really nice to have built in.

**Comment by ailin-nemui** [comment]
Tagmo also has a TP editor https://github.com/HiddenRamblings/TagMo/blob/master/app/src/main/java/com/hiddenramblings/tagmo/EditorTP.java
